// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCE_7wA29LHJWK_43If0o96S5IPLaLrrU',
    appId: '1:233864881789:web:a5a66977ad0976109d3314',
    messagingSenderId: '233864881789',
    projectId: 'digital-restaurant-d1f92',
    authDomain: 'digital-restaurant-d1f92.firebaseapp.com',
    storageBucket: 'digital-restaurant-d1f92.firebasestorage.app',
    measurementId: 'G-ZK3CBR83ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_D1Ac2JeXA_ffySsZKfPQl-0QJSfMtGQ',
    appId: '1:233864881789:android:ab22784ae725af4a9d3314',
    messagingSenderId: '233864881789',
    projectId: 'digital-restaurant-d1f92',
    storageBucket: 'digital-restaurant-d1f92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzhBp9XF8q9lDIosGsjhFdCuSppLcByEg',
    appId: '1:233864881789:ios:c14f1ced315dd5fd9d3314',
    messagingSenderId: '233864881789',
    projectId: 'digital-restaurant-d1f92',
    storageBucket: 'digital-restaurant-d1f92.firebasestorage.app',
    iosBundleId: 'com.example.digitalRestaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzhBp9XF8q9lDIosGsjhFdCuSppLcByEg',
    appId: '1:233864881789:ios:c14f1ced315dd5fd9d3314',
    messagingSenderId: '233864881789',
    projectId: 'digital-restaurant-d1f92',
    storageBucket: 'digital-restaurant-d1f92.firebasestorage.app',
    iosBundleId: 'com.example.digitalRestaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCE_7wA29LHJWK_43If0o96S5IPLaLrrU',
    appId: '1:233864881789:web:f2d4e1c73c2ae9f29d3314',
    messagingSenderId: '233864881789',
    projectId: 'digital-restaurant-d1f92',
    authDomain: 'digital-restaurant-d1f92.firebaseapp.com',
    storageBucket: 'digital-restaurant-d1f92.firebasestorage.app',
    measurementId: 'G-CP7YB4F12Z',
  );
}
